# Build Stage
FROM node:16.3 AS development
# Set the working directory.
WORKDIR /healthy_app

# Copy the package.json file.

COPY package*.json /healthy_app/

# Install application dependencies.
RUN npm install

# Copy the rest of the application files.
COPY . .


# Expose the port.
EXPOSE 3000

# Run the application.
CMD ["npm", "start"]