const {
  NODE_ENV,
  REACT_APP_HEALTHY,
  REACT_APP_HEALTHY_APP,
  REACT_APP_GATEWAY_TOKEN,
} = process.env;

export const ENV = NODE_ENV;
export const CONNECTIONS = {
  API_HEALTHY: REACT_APP_HEALTHY,
  APP: REACT_APP_HEALTHY_APP,
};

export const TOKENS = {
  GATEWAY_TOKEN: REACT_APP_GATEWAY_TOKEN,
};
